import './globals.css'
import Provider from '@/SessionProvider'

export const metadata = {
  title: 'Social Red',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
        {children}
      </Provider>
      </body>
    </html>
  )
}
